plugins {
	id 'java'
	id 'com.gradleup.shadow' version '9.3.1'
}

dependencies {
	implementation 'org.javassist:javassist:3.29.2-GA'
	testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
	testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
	useJUnitPlatform()
	testLogging {
		events "passed", "skipped", "failed"
		exceptionFormat = "full"
	}
}

jar {
	enabled = false
}

shadowJar {
	archiveFileName = 'storm-bootstrap.jar'

	manifest {
		attributes(
				'Premain-Class': 'io.pzstorm.storm.StormBootstrapper',
				'Can-Redefine-Classes': 'true',
				'Can-Retransform-Classes': 'true'
				)
	}
}

tasks.build.dependsOn tasks.shadowJar
