package io.pzstorm.storm.bullet.collision.dispatch;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;

import io.pzstorm.storm.UnitTest;
import io.pzstorm.storm.bullet.collision.narrowphase.btDiscreteCollisionDetectorInterface;
import io.pzstorm.storm.bullet.collision.shapes.btBoxShape;
import io.pzstorm.storm.bullet.collision.shapes.btSphereShape;
import io.pzstorm.storm.bullet.collision.shapes.btTriangleShape;
import io.pzstorm.storm.bullet.linearmath.btScalar;
import io.pzstorm.storm.bullet.linearmath.btTransform;
import io.pzstorm.storm.bullet.linearmath.btVector3;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.zip.GZIPInputStream;
import org.junit.jupiter.api.Test;

/**
 * Bit-exact differential tests against stock Bullet 2.82 (gcc 10.5 -O3 -DBT_USE_DOUBLE_PRECISION,
 * x86-64). Reference vectors were generated by a C++ driver kept outside the repo; each line holds
 * the inputs (hex doubles) followed by the expected outputs.
 */
class DispatchAlgorithmsDifferentialTest implements UnitTest {

    private static List<String[]> load(String name) throws IOException {
        List<String[]> out = new ArrayList<>();
        try (InputStream is =
                        DispatchAlgorithmsDifferentialTest.class.getResourceAsStream(
                                "dispatch-" + name + ".txt.gz");
                BufferedReader r =
                        new BufferedReader(
                                new InputStreamReader(
                                        new GZIPInputStream(is), StandardCharsets.US_ASCII))) {
            String line;
            while ((line = r.readLine()) != null) out.add(line.trim().split(" "));
        }
        return out;
    }

    /** Token cursor over one reference line. */
    private static final class Cur {
        final String[] t;
        int i;

        Cur(String[] t) {
            this.t = t;
        }

        String s() {
            return t[i++];
        }

        double d() {
            return Double.longBitsToDouble(Long.parseUnsignedLong(s(), 16));
        }

        int n() {
            return Integer.parseInt(s());
        }

        btVector3 v() {
            double x = d(), y = d(), z = d();
            return new btVector3(x, y, z);
        }

        btTransform tr() {
            btTransform t = new btTransform();
            double[] m = new double[9];
            for (int k = 0; k < 9; k++) m[k] = d();
            t.getBasis().setValue(m[0], m[1], m[2], m[3], m[4], m[5], m[6], m[7], m[8]);
            t.setOrigin(v());
            return t;
        }
    }

    private static void eq(double expected, double actual, String what) {
        assertEquals(
                Double.doubleToRawLongBits(expected),
                Double.doubleToRawLongBits(actual),
                () -> what + ": expected " + expected + " got " + actual);
    }

    private static void eq(btVector3 e, btVector3 a, String what) {
        eq(e.x(), a.x(), what + ".x");
        eq(e.y(), a.y(), what + ".y");
        eq(e.z(), a.z(), what + ".z");
    }

    /** Records every addContactPoint and checks it against the expected "C n p d" tokens. */
    private static final class Checker extends btDiscreteCollisionDetectorInterface.Result {
        final Cur c;
        final String ctx;
        int count;

        Checker(Cur c, String ctx) {
            this.c = c;
            this.ctx = ctx;
        }

        @Override
        public void setShapeIdentifiersA(int partId0, int index0) {}

        @Override
        public void setShapeIdentifiersB(int partId1, int index1) {}

        @Override
        public void addContactPoint(
                btVector3 normalOnBInWorld, btVector3 pointInWorld, double depth) {
            String w = ctx + " contact " + count;
            assertEquals("C", c.s(), w + ": Java reported more contacts than C++");
            eq(c.v(), normalOnBInWorld, w + " normal");
            eq(c.v(), pointInWorld, w + " point");
            eq(c.d(), depth, w + " depth");
            count++;
        }

        void end() {
            assertEquals(
                    "E", c.s(), ctx + ": C++ reported more contacts than Java (" + count + ")");
        }
    }

    @Test
    void boxBoxDetectorMatchesUpstream() throws IOException {
        List<String[]> lines = load("boxbox");
        assertEquals(1000, lines.size());
        int ln = 0;
        for (String[] line : lines) {
            Cur c = new Cur(line);
            btVector3 h0 = c.v(), h1 = c.v();
            btTransform t0 = c.tr(), t1 = c.tr();
            btBoxShape b0 = new btBoxShape(h0), b1 = new btBoxShape(h1);
            btBoxBoxDetector det = new btBoxBoxDetector(b0, b1);
            btDiscreteCollisionDetectorInterface.ClosestPointInput in =
                    new btDiscreteCollisionDetectorInterface.ClosestPointInput();
            in.m_maximumDistanceSquared = btScalar.BT_LARGE_FLOAT;
            in.m_transformA.set(t0);
            in.m_transformB.set(t1);
            Checker chk = new Checker(c, "boxbox line " + ln);
            det.getClosestPoints(in, chk, null);
            chk.end();
            ln++;
        }
    }

    @Test
    void sphereTriangleDetectorMatchesUpstream() throws IOException {
        List<String[]> lines = load("spheretri");
        assertEquals(1000, lines.size());
        int ln = 0;
        for (String[] line : lines) {
            Cur c = new Cur(line);
            btVector3 a = c.v(), b = c.v(), cc = c.v();
            double r = c.d(), thr = c.d();
            boolean swap = c.n() != 0;
            btTransform ts = c.tr(), tt = c.tr();
            SphereTriangleDetector det =
                    new SphereTriangleDetector(
                            new btSphereShape(r), new btTriangleShape(a, b, cc), thr);
            btDiscreteCollisionDetectorInterface.ClosestPointInput in =
                    new btDiscreteCollisionDetectorInterface.ClosestPointInput();
            in.m_maximumDistanceSquared = btScalar.BT_LARGE_FLOAT;
            in.m_transformA.set(ts);
            in.m_transformB.set(tt);
            Checker chk = new Checker(c, "spheretri line " + ln);
            det.getClosestPoints(in, chk, null, swap);
            chk.end();
            ln++;
        }
    }

    @Test
    void capsuleCapsuleDistanceMatchesUpstream() throws IOException {
        List<String[]> lines = load("capsule");
        assertEquals(1000, lines.size());
        int ln = 0;
        for (String[] line : lines) {
            Cur c = new Cur(line);
            double lA = c.d(), rA = c.d(), lB = c.d(), rB = c.d(), thr = c.d();
            int aA = c.n(), aB = c.n();
            btTransform tA = c.tr(), tB = c.tr();
            btVector3 n = new btVector3(0, 0, 0), p = new btVector3(0, 0, 0);
            double d =
                    btConvexConvexAlgorithm.capsuleCapsuleDistance(
                            n, p, lA, rA, lB, rB, aA, aB, tA, tB, thr);
            String w = "capsule line " + ln;
            assertEquals("R", c.s());
            eq(c.d(), d, w + " distance");
            eq(c.v(), n, w + " normal");
            eq(c.v(), p, w + " point");
            ln++;
        }
    }

    @Test
    void hashedSimplePairCacheMatchesUpstream() throws IOException {
        List<String[]> lines = load("paircache");
        btHashedSimplePairCache cache = new btHashedSimplePairCache();
        int ln = 0;
        for (String[] line : lines) {
            Cur c = new Cur(line);
            String w = "paircache line " + ln;
            switch (c.s()) {
                case "A" -> {
                    int a = c.n(), b = c.n();
                    btSimplePair p = cache.addOverlappingPair(a, b);
                    assertEquals(c.n(), p.m_indexA, w);
                    assertEquals(c.n(), p.m_indexB, w);
                }
                case "R" -> {
                    int a = c.n(), b = c.n();
                    Object u = cache.removeOverlappingPair(a, b);
                    assertEquals(c.n(), u != null ? 1 : 0, w);
                }
                case "F" -> {
                    int a = c.n(), b = c.n();
                    int expectedIdx = c.n();
                    btSimplePair p = cache.findPair(a, b);
                    if (expectedIdx < 0) {
                        assertNull(p, w);
                    } else {
                        assertNotNull(p, w);
                        assertEquals(
                                p, cache.getOverlappingPairArray().get(expectedIdx), w + " index");
                    }
                }
                case "N" -> assertEquals(c.n(), cache.getNumOverlappingPairs(), w);
                case "D" -> {
                    int n = c.n();
                    assertEquals(n, cache.getNumOverlappingPairs(), w);
                    for (int k = 0; k < n; k++) {
                        String[] ab = c.s().split(":");
                        btSimplePair p = cache.getOverlappingPairArray().get(k);
                        assertEquals(Integer.parseInt(ab[0]), p.m_indexA, w + " pair " + k);
                        assertEquals(Integer.parseInt(ab[1]), p.m_indexB, w + " pair " + k);
                    }
                }
                default -> throw new AssertionError(w + ": bad tag");
            }
            ln++;
        }
    }
}
