function stormLoaderVerificationCheck()
    if Storm then
        print("Storm is loaded successfully")
    else
        print("================================================================================")
        print("  STORM BOOTSTRAP JAR IS NOT LOADED")
        print("================================================================================")
        print("")
        print("  The Storm mod requires the bootstrap jar to be loaded as a Java agent on")
        print("  your server startup. You must modify your start-server.sh (Linux) or")
        print("  StartServer64.bat (Windows).")
        print("")
        print("  REQUIRED CHANGES:")
        print("")
        print("  Add the following JVM flags to your server launch command:")
        print("")
        print("    -javaagent:./steamapps/workshop/content/108600/3675499853/mods/storm/bootstrap/storm-bootstrap.jar")
        print("    -Dstorm.server=true")
        print("")
        print("  Example (Linux start-server.sh):")
        print("    \"${INSTDIR}/jre64/bin/java\" \\")
        print("      -javaagent:./steamapps/workshop/content/108600/3675499853/mods/storm/bootstrap/storm-bootstrap.jar \\")
        print("      -Dstorm.server=true \\")
        print("      ... other flags ...")
        print("")
        print("================================================================================")
        getCore():quitToDesktop()
    end
end

Events.OnGameBoot.Add(stormLoaderVerificationCheck)
